#!/usr/bin/env bash
set -euxo pipefail

python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
python 3exp.py
