#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 
import sys
import time
# usage : makeblog xxx.md

updatetime = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))
date = updatetime.split(' ',1)[0]
source = open(sys.argv[1], 'r')
title = source.readline().replace('# ', '').replace('\n', '')
content = source.read()
source.close()

blogname = date + '-' + sys.argv[1]
target = open(blogname, 'w')
head = '---\n'
head += 'layout: post\n'
head += 'title: "{}"\n'.format(title)
head += 'date: {}\n'.format(updatetime)
category = raw_input('category? ')
tags = raw_input('tags? ')
head += 'categories: {}\n'.format(category)
head += 'tags: {}\n'.format(tags)
head += '---\n'
target.write(head)
discription = raw_input('discription:')
target.write(discription+'\n')
target.write(content)
target.close()
print '\033[0;32mdone'
